annotations:
  created: "2025-07-25T05:16:31Z"
  revision: 24d51e8ff3f6df032f30afd349bbe173c3117ad2
apiVersion: v2
appVersion: 2.0.17-dev
description: Deploy the MX Grid Manager app-orch pod
name: orch-ui-app-orch
type: application
version: 2.0.17-dev
